config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy] do
  	resources :comments, only: [:index, :create], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, :dependent => :destroy
    has_one_attached :image
    validate :image_presence
    def image_presence
        errors.add(:image, "can't be blank") unless image.attached?
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
    	@comments = @post.comments.includes(:user)
  	end
	def create
		#@comment = @post.comments.create(comment_params)
		@post = Post.find_by_id(params[:post_id])
		@comment = @post.comments.create(comment_params)
		if @comment.save
			redirect_to @post
		else
			flash.now[:danger] = "error"
		end
	end
	private
    def comment_params
    	params.required(:comment).permit :user_id, :post_id, :content
  	end

	#private
	#def set_post
	#	@post = User.posts.find(params[:post_id])
	#end
	#def set_user
	#	@user = User.find(params[:user_id])
	#end
	#def comment_params
	#	params[:comment].permit()
	#end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end

 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
      Post.create(post_params)
      redirect_to root_path
    end
    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy
      redirect_to user_path(current_user)
    end

    def show
      @post = Post.find(params[:id])
    end
    private
    def post_params
      params.require(:post).permit(:description, :image, :user_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user  = User.find(params[:id])
	    @posts = @user.posts.order(created_at: :desc)

	end
	def edit
	    @user=User.find(params[:id])
	end
	def update
      current_user.update(user_params)
      redirect_to current_user
    end
    private
    def user_params
      params.require(:user).permit(:username, :name, :website,
                                   :bio, :email, :phone, :gender, :avatar)
    end

    def destroy
    	user =User.find(params[:id])
    	user.destroy
    	redirect_to user_session, :notice => "Log out sucsseful"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_list_comment.html.erb
<% post.comments.each do |comment| %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user),
          class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %

app/views/comments/_upload_form.html.erb
        <div class="upload-comment">
            <%= form_with scope: :comment, local: true do |form| %>
            <div class="form-group">
                <%= form.label :comment %>
                <%= form.text_field :comment %>
                <%= form.submit %>
            </div>

            <% end %>
        </div>

app/views/home/_post.html.erb
<section class="post">
  <div class="user">
    <div class="avatar">
      <% if post.user.avatar.attached? %>
        <%= link_to user_path(post.user) do %>
          <%= image_tag post.user.avatar %>
        <% end %>
      <% end %>
    </div>
    <%= link_to post.user.username, user_path(post.user), class: 'username' %>
  </div>
  <%= image_tag post.image, class: 'main-image' %>
  <div class="description">
    <%= render partial: "posts/description", locals: {post: post} %>
  </div>
</section>

app/views/home/_upload_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :description,placeholder: "How are you today  ..." %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/index.html.erb
			<div class="homepage">
				<% if user_signed_in? %>
					<div class='form-upload'>
			    	<%= render 'upload_form' %>
			  	</div>

				<div class="posts">
				  <% @posts.each do |post| %>
				    <section class="post">
				      <div class="user">
			    	<div class="avatar">
			    		      <% if post.user.avatar.attached? %>
        						<%= link_to user_path(post.user) do %>
          							<%= image_tag post.user.avatar %>
        						<% end %>
      						<% end %>
			    	</div>
			    <%= link_to post.user.username, user_path(post.user), class: 'username' %>
				</div>
				  <%= image_tag post.image, class: 'main-image' %>
				  <div class="description">
				    <%= post.description %>
				  </div>
				  <!---div class="comment">
      					<%#=post.comments.username  %>
      					<%#=post.comments.comment %>
				  </div---->
				    </section>
				  <% end %>
				  <%= paginate @posts %>
				</div>
	            <% else %>
	            <!---a href="<%= new_user_session_path%>">
	              <i class="fa fa-sign-in"></i>
	            </a--->
	          <% end %>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram.com</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%=new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2019 WEB PROJECT 20191 </p>
      </nav>
    </footer>
  </body>
</html

app/views/posts/_comment_list.html.erb
<% @post.comments.each do |comment| %>
    <span>
      <strong>
        <%= link_to comment.user.username, user_path(comment.user),
          class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

app/views/posts/_comment_upload.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
  <%= f.label :comment %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, class: "form-control comment-input border-0",
     placeholder: "Add a comment ...", autocomplete: :off %>
  <%= f.submit %>
<% end %>

app/views/posts/_description.html.erb
<% post.description.to_s.split(' ').each do |word| %>
  <% if word.start_with?('#') %>
    <%= link_to word, search_path(query: word) %>
  <%else %>
    <%= word %>
  <%end %>
<% end %>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <%= render partial: "description", locals: {post: @post} %>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= button_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }%>
      <% end %>
    </div>
    <div class="comment">
      <%=render 'comment_list',post: @post  %>
      <%=render 'comment_upload',post: @post %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <%end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if @user == current_user %>
          <a class="edit-profile" href="<%= edit_user_path(@user) %>">
            <button>Edit Profile</button>
          </a>
          <a class="log-out" href="<%=destroy_user_session_path%>">
            <i class="fa fa-sign_in"></i>
            <button>Log Out</button>
          </a>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>100</span> followers</li>
        <li><span>300</span> following</li>
      </ul>
      <h2 class="name"><%=@user.name %></h2>
      <%=link_to @user.website, @user.website, class: 'website' %>
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>